 version: '2'
 services:
   postgres:
     image: postgres
   web:
     volumes:
       - ~/dev/SOLAR/solarpilot:/package
     build: .
     ports:
       - "80:80"
     depends_on:
       - postgres
