# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 15:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='total_units',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
