# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0002_grid_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionmeasurement',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
