# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='co2multiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='co2multiplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gridpricemultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='gridpricemultiplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kmmultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='kmmultiplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solarpricemultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='solarpricemultiplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
