# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0003_consumptionmeasurement_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmeasurement',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
