# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 14:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0003_auto_20170516_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='mRID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='up_code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
            preserve_default=False,
        ),
    ]
