# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0004_auto_20170519_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='server_ip',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
