# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0005_auto_20170311_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptionmeasurement',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='productionmeasurement',
            old_name='time',
            new_name='timestamp',
        ),
    ]
