# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0006_auto_20170312_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelsToInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infographics.Building')),
            ],
        ),
    ]
