# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0008_panelstoinstall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelstoinstall',
            name='use',
            field=models.BooleanField(default=True),
        ),
    ]
