# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('infographics', '0011_create-superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermethods',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='UserMethods',
        ),
    ]
